### PR TITLE
Add validator client and node public addresses

### PR DESCRIPTION
**Pull request by WadeBarnes**
- Add the public client and node addresses to the output of `fetch-validator-status`.
  - The public addresses come from the pool information.  The nodes themselves are unaware of their public addresses.  The addresses are added to the node summary in order to ensure the results from `get_validator_info` are unmodified.
  - Requires a version of `bcgovimages/von-image:next-1` built with https://github.com/hyperledger/indy-vdr/commit/ce0e7c42491904e0d563f104eddc2386a52282f7.  The address fields will not be included in the summary results when using a previous version of `bcgovimages/von-image:next-1`.

Signed-off-by: Wade Barnes <wade.barnes@shaw.ca>

### CODE REVIEW

**Comment by WadeBarnes** [comment]
Changes have been tested using the existing version and a new (locally built) version of `bcgovimages/von-image:next-1`.  Results have been verified against the records for Sovrin BuilderNet, StagingNet, and MainNet ledgers.

**Comment by WadeBarnes** [comment]
PR and request for new build of `bcgovimages/von-image:next-1`; https://github.com/PSPC-SPAC-buyandsell/von-image/pull/23

**Comment by WadeBarnes** [comment]
Related `indy-vdr` ticket and PR;
- https://github.com/hyperledger/indy-vdr/issues/43
- https://github.com/hyperledger/indy-vdr/pull/47

**Comment by WadeBarnes** [comment]
Example output:
```
  {
    "name": "FoundationBuilder",
    "client-address": "tcp://35.161.146.16:9702",
    "node-address": "tcp://50.112.53.5:9701",
    "status": {
      "ok": true,
      "uptime": "39 days, 1:55:36",
      "timestamp": 1601229678,
      "software": {
        "indy-node": "1.12.4",
        "sovrin": "1.1.89"
      }
    }
  }
```

**Comment by WadeBarnes** [comment]
The new `bcgovimages/von-image:next-1` image is available ; https://hub.docker.com/r/bcgovimages/von-image/tags

**Comment by WadeBarnes** [comment]
To ensure the new version of `bcgovimages/von-image:next-1` delete any locally cached version; `docker image rm bcgovimages/von-image:next-1`

**Comment by swcurran** [comment]
Suggest adding an error status check on the docker build and terminating on fail.  I've been running the command from the parent directory, and the docker build has been failing, but the app running fine (because of the existing image).  The command would run fine but I didn't get the update because even though I deleted the base image, the built image still remained.

Anyway, once that was sorted out -- all good.  :-).

**Review by swcurran — APPROVED** [review]
LGTM

**Pull request merged**
