### PR TITLE
Build docker

### PR DESCRIPTION
**Pull request by GuillaumeBourque-QC**
Hello this as not been tested but should be near a working solution.

Since the idlab depot is not updated very often we could host a docker image right in GitHub container registry.

In order to use this workflow we need to add a tag to a release like so:

```
git tag v2.4.5
git push origin v2.4.5
```

The resulting container is not public but from my readings, this cli (gh) if you have it can make the container publicly avail,

```
gh api --method PATCH /user/packages/container/hyperledger/indy-node-monitor/visibility --input '{"visibility":"public"}'
```

### CODE REVIEW

**Review by WadeBarnes — CHANGES_REQUESTED** [review]
I think it would be better to do the build when a release is created, and to use the standard docker related actions rather than the docker command directly.

Examples:
- https://github.com/openwallet-foundation/acapy/blob/main/.github/workflows/publish.yml
- https://github.com/BCDevOps/backup-container/blob/master/.github/workflows/bc-postgres-docker-publish.yaml

Examples of generating the image tags:
- https://github.com/BCDevOps/backup-container/blob/master/.github/workflows/bc-postgres-docker-publish.yaml#L19-L34
- https://github.com/bcgov/traction/blob/main/.github/actions/build_acapy/action.yaml#L58-L67

**Comment by GuillaumeBourque-QC** [comment]
No problem at all using the default action which I was not aware of (I only look at https://docs.github.com/packages/working-with-a-github-packages-registry/working-with-the-container-registry and some googling).

Do you want to to change the workflow with your proposition ?  Since we are working in gitlab internally it may be easier for you to test from your repos, or if time is missing I can try to look at it next week ?

**Comment by WadeBarnes** [comment]
> No problem at all using the default action which I was not aware of (I only look at https://docs.github.com/packages/working-with-a-github-packages-registry/working-with-the-container-registry and some googling).
> 
> Do you want to to change the workflow with your proposition ? Since we are working in gitlab internally it may be easier for you to test from your repos, or if time is missing I can try to look at it next week ?

You should be able to test any changes you make, easily, on your fork in GitHub.

**Comment by GuillaumeBourque-QC** [comment]
Hello Wade,

I tested some of the provided example but seem more complicated and dont see the value for this repos.

Also from GitHub Action examples that you can see when you create from their template they all use docker build.

image

So I did several test and came up with a working solution based on tags. you can run manually the workflow and provide a tag version or it will build on the latest tag.

Maybe we could start from this ? I will push my code in a few minutes ?

**Comment by GuillaumeBourque-QC** [comment]
I can't get out of this because of 1 commit which is not sign even if I did tried to sing all my commit, it's friday night here, will continue next week...
 
 
 Maybe I'll close this PR an open a new one for simplicity and to avoid all these comit.

**Comment by GuillaumeBourque-QC** [comment]
Will continue in the new PR https://github.com/hyperledger/indy-node-monitor/pull/80

**Pull request closed without merging**
