### PR TITLE
Added a way to not use the -it mode for docker easily by setting the CM env variable on run #13

### PR DESCRIPTION
**Pull request by swcurran**

### CODE REVIEW

**Comment by swcurran** [comment]
Addresses #13 -- @lohanspies .  However, I'm not sure we need the `-it` at all.  @WadeBarnes -- can we just leave off the -it, since all we do is write the output to standard out?

**Comment by lohanspies** [comment]
@swcurran Suggest we make the default mode to run without `-it` i.e. `cron mode` and then change the parameter to DM (Developer Mode) that will enable the developer to attach to bash shell where needed. If this will never be a requirement then it might as well just be removed completely.

**Comment by WadeBarnes** [comment]
The `-it` in `run.sh` is not required.

**Comment by swcurran** [comment]
Will do.

**Comment by swcurran** [comment]
I turned it off by default, but left the "IM" (interactive mode) env variable that if set turns on interactive mode.  That might be unneeded, but hey, why not?

**Pull request merged**
