### PR TITLE
Initial implementation of plugin architecture.

### PR DESCRIPTION
**Pull request by KoleBarnes**
Including documentation.

### CODE REVIEW

**Comment by WadeBarnes** [comment]
@lohanspies, @lynnbendixsen

**Comment by lohanspies** [comment]
> @lohanspies, @lynnbendixsen

Brilliant! Thank you @WadeBarnes and @KoleBarnes. This is a massive improvement.

**Comment by WadeBarnes** [comment]
A note for @swcurran.  This is the initial framework.  The additional automated node monitoring plugin(s) will be added once this is merged.

**Comment by WadeBarnes** [comment]
> > @lohanspies, @lynnbendixsen
> 
> Brilliant! Thank you @WadeBarnes and @KoleBarnes. This is a massive improvement.

It's all @KoleBarnes, I'm just providing support and a little guidance.

**Review by swcurran — COMMENTED** [review]
LGTM!! Nice work.  I've not had a chance to run these, so am not marking approved yet (although others can), but I really like this approach.  Even better than the bash pipeline way :-)

**Review by WadeBarnes — APPROVED** [review]
I've been using this heavily over the last few days while troubleshooting a few nodes on Sorin StagingNet.  The only issue I discovered was one that existed in my original code.

**Pull request merged**
